# Generated by Django 2.2.7 on 2020-07-03 12:42

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=5000)),
                ('progress_percent', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_project',
            name='project_id',
        ),
        migrations.AddField(
            model_name='user_project',
            name='end_date',
            field=models.DateTimeField(default='2009-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_project',
            name='progress_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user_project',
            name='project_name',
            field=models.CharField(default='Sample', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_project',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='sample', editable=False, populate_from='project_name', unique_with=['id']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_project',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default='2009-10-10'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='project_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=5000)),
                ('status', models.CharField(choices=[('C1', 'Cancel'), ('C2', 'Not Started'), ('C3', 'In Progress'), ('C4', 'Done')], max_length=2)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.project_module')),
            ],
        ),
        migrations.AddField(
            model_name='project_module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.user_project'),
        ),
    ]
