# Generated by Django 2.2.7 on 2020-07-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20200704_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_module',
            name='progress_percent',
        ),
    ]
