# Generated by Django 2.2.7 on 2020-07-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_remove_project_module_progress_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_task',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_task',
            name='status',
            field=models.CharField(choices=[('C1', 'Cancel'), ('C2', 'Not Started'), ('C3', 'In Progress'), ('C4', 'Done')], default='C2', max_length=2),
        ),
        migrations.AlterField(
            model_name='project_task',
            name='task_name',
            field=models.CharField(default='Try', max_length=5000),
        ),
    ]
