# Generated by Django 2.2.7 on 2020-07-06 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20200705_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_task',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
