# Generated by Django 2.2.7 on 2020-07-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_project_task_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_task',
            old_name='last_updated',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='project_task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
