# Generated by Django 2.2.7 on 2020-07-07 18:45

import autoslug.fields
from django.db import migrations
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20200706_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_project',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='project_name', slugify=scheduler.models.generate_random_url, unique_with=['id']),
        ),
    ]
