# Generated by Django 2.2.7 on 2020-07-09 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_project_task_priority_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_project',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
