# Generated by Django 2.2.7 on 2020-07-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_user_project_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='pre_launch_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=10000)),
            ],
        ),
    ]
