# Generated by Django 2.2.7 on 2020-07-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_pre_launch_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_task',
            name='task_name',
            field=models.CharField(max_length=5000),
        ),
    ]
