# Generated by Django 2.2.7 on 2020-07-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20200716_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot_left',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField()),
            ],
        ),
    ]
